services:
  auth_service:
    build: ./auth_service
    container_name: auth_service
    depends_on:
      - auth_service_db_init
    ports:
      - 80:3000
    volumes:
      - ./auth_service/dist:/app/dist
      - sqlite_db_data:/sqlite_db_data
    networks:
      - transcendence


  auth-db-service:
    build:
      context: ./auth_service_db
      dockerfile: Dockerfile
    container_name: auth_service_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: auth_db
    volumes:
      - services_auth_db_data:/var/lib/postgresql/data # named volume
    networks:
      - transcendence


  auth_service_sqlite:
    build:
      context: ./auth_service_sqlite
      dockerfile: Dockerfile
    container_name: auth_service_sqlite
    ports:
      - 81:3000
    volumes:
      - ./auth_service_sqlite/dist:/app/dist
      - sqlite_db_data:/sqlite_db_data
    networks:
      - transcendence

  auth_service_db_init:
    build:
      context: ./auth_service_db_init
      dockerfile: Dockerfile
    container_name: auth_service_db_init
    volumes:
      - sqlite_db_data:/sqlite_db_data
    networks:
      - transcendence


networks:
  transcendence:
    driver: bridge


volumes:
  # sqlite
  sqlite_db_data:
  # postgres
  services_auth_db_data: